'use strict';
// =============================================================
// src/emails.js — Email formatting via Gmail API (nodemailer)
// Replaces: MailApp.sendEmail() in Apps Script
// =============================================================

const nodemailer = require('nodemailer');
const { SPREADSHEET_ID, SHEETS, GMAIL_USER, GMAIL_APP_PASSWORD, EMAIL_RECIPIENTS } = require('./config');
const { getValues, appendRows } = require('./sheets');

let _transporter = null;

function getTransporter() {
  if (_transporter) return _transporter;
  _transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: GMAIL_USER,
      pass: GMAIL_APP_PASSWORD,
    },
  });
  return _transporter;
}

/**
 * Send the daily picks email.
 * Trigger 9: ~6:30 AM ET daily
 */
async function sendDailyPicksEmail() {
  console.log('[emails] Sending daily picks email...');

  const [mlbRows, nbaRows, propCombos, propsRaw] = await Promise.all([
    getValues(SPREADSHEET_ID, SHEETS.MLB_PREDICTIONS),
    getValues(SPREADSHEET_ID, SHEETS.NBA_PREDICTIONS),
    getValues(SPREADSHEET_ID, SHEETS.PLATFORM_COMBOS),
    getValues(SPREADSHEET_ID, SHEETS.PLAYER_PROPS),
  ]);

  // Prop_Combos columns:
  // 0=Timestamp 1=League 2=Player 3=Market 4=Line 5=Direction 6=Book
  // 7=BookOdds 8=BookProb 9=ConsensusProb 10=Edge 11=Game
  const formatPropRows = () => {
    if (propCombos && propCombos.length > 1) {
      return propCombos.slice(1, 16).map(r => {
        const edgeNum = parseFloat(r[10]);
        const edgeLabel = Number.isFinite(edgeNum) ? `${edgeNum.toFixed(1)}%` : (r[10] || '');
        const elite = Number.isFinite(edgeNum) && edgeNum >= 2 ? ' ⭐' : '';
        return `<tr><td>${r[2] || ''}</td><td>${r[3] || ''} ${r[5] || ''} ${r[4] || ''}</td><td>${r[6] || ''} @ ${r[7] || ''}</td><td>${edgeLabel}${elite}</td></tr>`;
      }).join('');
    }
    if (propsRaw && propsRaw.length > 1) {
      // Fallback: raw Player_Props rows, no edge math
      return propsRaw.slice(1, 16).map(r =>
        `<tr><td>${r[3] || ''}</td><td>${r[7] || ''} ${r[4] || ''} ${r[6] || ''}</td><td>${r[2] || ''} @ ${r[5] || ''}</td><td>—</td></tr>`
      ).join('');
    }
    return '<tr><td colspan="4"><em>No props today.</em></td></tr>';
  };

  const formatPicks = (rows, sport) => {
    if (!rows || rows.length <= 1) return `<p><em>No ${sport} picks today.</em></p>`;
    return rows.slice(1).map(r =>
      `<tr><td><strong>${r[2] || ''}</strong></td><td>${r[3] || ''}</td><td>${r[4] || ''}</td><td>${r[5] || ''}/10</td></tr>`
    ).join('');
  };

  const today = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

  const html = `
<!DOCTYPE html>
<html>
<head><style>
  body { font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; }
  h1 { color: #1a1a2e; }
  h2 { color: #16213e; border-bottom: 2px solid #0f3460; padding-bottom: 5px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
  th { background: #0f3460; color: white; padding: 8px; text-align: left; }
  td { padding: 8px; border-bottom: 1px solid #eee; }
  tr:hover { background: #f5f5f5; }
  .footer { color: #666; font-size: 12px; margin-top: 30px; }
</style></head>
<body>
  <h1>🎯 Shadow Bets Daily Picks</h1>
  <p>${today}</p>
  
  <h2>⚾ MLB Picks</h2>
  <table>
    <tr><th>Team</th><th>Bet Type</th><th>Line</th><th>Confidence</th></tr>
    ${formatPicks(mlbRows, 'MLB')}
  </table>
  
  <h2>🏀 NBA Picks</h2>
  <table>
    <tr><th>Team</th><th>Bet Type</th><th>Line</th><th>Confidence</th></tr>
    ${formatPicks(nbaRows, 'NBA')}
  </table>
  
  <h2>🎰 Player Props — Top Picks</h2>
  <p style="font-size:12px;color:#666;margin-top:-5px;">⭐ = elite edge (≥2% over consensus)</p>
  <table>
    <tr><th>Player</th><th>Pick</th><th>Book / Odds</th><th>Edge</th></tr>
    ${formatPropRows()}
  </table>
  
  <div class="footer">
    <p>Generated by Shadow Bets automation. For informational purposes only.</p>
  </div>
</body>
</html>
`;

  const transporter = getTransporter();
  await transporter.sendMail({
    from: GMAIL_USER,
    to: EMAIL_RECIPIENTS.join(', '),
    subject: `🎯 Shadow Bets Picks — ${today}`,
    html,
  });

  // Log to EmailLog sheet
  const ts = new Date().toISOString();
  await appendRows(SPREADSHEET_ID, SHEETS.EMAIL_LOG, [
    [ts, 'DailyPicks', EMAIL_RECIPIENTS.join(','), 'sent', ''],
  ]);

  console.log(`[emails] Daily picks email sent to ${EMAIL_RECIPIENTS.length} recipients`);
}

/**
 * Send a performance summary email.
 * Trigger 13: Sunday evening
 */
async function sendPerformanceSummary() {
  console.log('[emails] Sending performance summary...');

  const perfRows = await getValues(SPREADSHEET_ID, SHEETS.PERFORMANCE);
  const recentRows = perfRows.slice(-8); // last 7 days + header

  const tableRows = recentRows.slice(1).map(r =>
    `<tr><td>${r[0] || ''}</td><td>${r[1] || ''}</td><td>${r[2] || ''}</td><td>${r[3] || ''}</td></tr>`
  ).join('');

  const html = `
<!DOCTYPE html>
<html>
<body style="font-family: Arial, sans-serif;">
  <h1>📊 Shadow Bets Weekly Performance</h1>
  <table style="width:100%;border-collapse:collapse;">
    <tr style="background:#0f3460;color:white;">
      <th style="padding:8px;">Date</th><th style="padding:8px;">Record</th><th style="padding:8px;">ROI</th><th style="padding:8px;">Bankroll</th>
    </tr>
    ${tableRows || '<tr><td colspan="4">No data yet.</td></tr>'}
  </table>
</body>
</html>
`;

  const transporter = getTransporter();
  await transporter.sendMail({
    from: GMAIL_USER,
    to: EMAIL_RECIPIENTS.join(', '),
    subject: '📊 Shadow Bets Weekly Performance Summary',
    html,
  });

  const ts = new Date().toISOString();
  await appendRows(SPREADSHEET_ID, SHEETS.EMAIL_LOG, [
    [ts, 'PerformanceSummary', EMAIL_RECIPIENTS.join(','), 'sent', ''],
  ]);

  console.log('[emails] Performance summary sent');
}

module.exports = { sendDailyPicksEmail, sendPerformanceSummary };
